"""Add phone field to users

Revision ID: 9245a3539aae
Revises: 9ebf271bdf81
Create Date: 2025-11-06 10:54:23.608005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9245a3539aae'
down_revision = '9ebf271bdf81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('month', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('week', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('men', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('women', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('youth_boys', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('youth_girls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('children_boys', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('children_girls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('attendance_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key(None, 'old_groups', ['old_group_id'], ['id'])
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'regions', ['region_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('district_id')
        batch_op.drop_column('region_id')
        batch_op.drop_column('state_id')
        batch_op.drop_column('phone')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('year')
        batch_op.drop_column('children_girls')
        batch_op.drop_column('children_boys')
        batch_op.drop_column('youth_girls')
        batch_op.drop_column('youth_boys')
        batch_op.drop_column('women')
        batch_op.drop_column('men')
        batch_op.drop_column('week')
        batch_op.drop_column('month')
        batch_op.drop_column('old_group_id')
        batch_op.drop_column('group_id')
        batch_op.drop_column('district_id')
        batch_op.drop_column('region_id')
        batch_op.drop_column('state_id')
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
